services:
    app_database:
        image: postgres:alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: app_database
        ports:
            - 5432:5432
        volumes:
            - app_database:/var/lib/postgresql/data
        networks:
            - src_default
    mailpit:
      image: 'axllent/mailpit:latest'
      ports:
          - '${FORWARD_MAILPIT_PORT:-1025}:1025'
          - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
      networks:
          - src_default
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis:/data'
        networks:
            - src_default
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
volumes:
    app_database:
        driver: local
    redis:
        driver: local
networks:
    src_default:
        driver: bridge